spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: nuri
    password: Password@1234
  mvc:
    view:
      prefix: /WEB-INF/views/ # Controller가 return을 할 때 접두사로 붙여주는 경로명
      suffix: .jsp # Controller가 return을 할 때 접미사로 붙여주는 경로명
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 프로젝트를 재실행할 때 마다 Table을 생성, 최초에만 Create, 이후에는 update로 변경
      use-new-id-generator-mappings: false # JPA가 사용하는 기본 넘버링 전략을 따라갈 것인가?(DB 전략을 따라가기 때문에 false)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #entity(Table)을 만들 때 변수 명 그대로 테이블에 필드를 만들어 줌
    show-sql: true # Console 창에 실행 된 SQL 쿼리문이 한 줄로 보임
    properties:
      hibernate:
        '[format_sql]': true # 한 줄로 보이는 SQL 쿼리문을 이쁘게 보여줌
        
  jackson:
    serialization:
      fail-on-empty-beans: false
    
server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  